services:
  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  jd-services:
    build: ./jdService
    container_name: jdService
    depends_on:
      - mongo
    ports:
      - "3001:3001"

  applicant-service:
    build: ./applicant-service
    container_name: applicant-service
    depends_on:
      - mongo
    ports:
      - "3002:3002"

  nginx:
    image: nginx:alpine
    container_name: nginxATS
    ports:
      - "8080:80"

volumes:
  mongo-data:
